### ISSUE TITLE
zoom and move buttons broken for mpl 3.7.0

### ISSUE THREAD

**Issue by Linusnie** [matplotlib/ipympl#516]
After installing jupyterlab and ipympl I'm able to make plots that can be displayed and resized, but the move and zoom buttons don't work. Tooltips are shown if I hover the cursor over the buttons, but clicking them gives no response. 

I also posted in https://github.com/matplotlib/ipympl/issues/70 which was closed as outdated

package versions:
```
ipykernel 6.21.2
ipympl 0.9.2
ipython 8.10.0
ipython-genutils 0.2.0
ipywidgets 8.0.4
jupyter_client 8.0.2
jupyter_core 5.2.0
jupyter-events 0.5.0
jupyter_server 2.2.1
jupyter_server_fileid 0.6.0
jupyter_server_terminals 0.4.4
jupyter_server_ydoc 0.6.1
jupyter-ydoc 0.2.2
jupyterlab 3.6.1
jupyterlab-darkside-ui 0.2.3
jupyterlab-pygments 0.2.2
jupyterlab_server 2.19.0
jupyterlab-widgets 3.0.5
```

`jupyter labextension list` returns the following:
```
jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
jupyter-matplotlib v0.11.2 enabled OK
@jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
@dunovank/jupyterlab_darkside_ui v0.2.3 enabled OK (python, jupyterlab_darkside_ui)
```

![Screenshot from 2023-02-14 23-40-58](https://user-images.githubusercontent.com/12471058/218880429-06e4e769-0232-4ef6-90b8-e40e73eac0ca.jpg)

**Comment by ianhi** [comment]
@Linusnie are you using ipympl in vscode or in jupyterlab?

**Comment by Linusnie** [comment]
> @Linusnie are you using ipympl in vscode or in jupyterlab?

I'm using jupyterlab

**Comment by ianhi** [comment]
Ok great. Two follow up questions:

1. Can you post a gif of you trying to use them?
2. Can you post the contents of the browser console after trying this here (see how to access https://balsamiq.com/support/faqs/browserconsole/)

**Comment by Linusnie** [comment]
sure! There's quite a bit of output in the console, most relevant might be this one: `Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early`? (last image)

![screencast](https://user-images.githubusercontent.com/12471058/218982698-953b98d5-c503-4668-9f36-2ab98d4486f5.gif)
![Screenshot from 2023-02-15 10-08-14](https://user-images.githubusercontent.com/12471058/218983573-602c3e2a-be29-49f0-ac58-e787f98040e7.png)
![Screenshot from 2023-02-15 10-09-08](https://user-images.githubusercontent.com/12471058/218983564-0e09ccb9-bc4d-48d9-9b85-a81113040eb0.png)
![Screenshot from 2023-02-15 10-09-23](https://user-images.githubusercontent.com/12471058/218983572-6618fe2a-4f8b-4c46-9ebd-8933273f25c6.png)

**Comment by Linusnie** [comment]
in case it's relevant, things like `ipywidgets.IntSlider(10)` works and I can interact with no issue

**Comment by ianhi** [comment]
Ahh indeed broken for the new matplotlib. Thank you for reporting!

> f I try the same notebook in vs code it prints out the following error message when I try to use the plot (not sure why it doesn't show up when using jupyterlab).

You can see the errors by going `View> Show Log Console` and changing thelevel to `info`

**Comment by ianhi** [comment]
I think the breakage is caused by https://github.com/matplotlib/matplotlib/pull/23473 which requires us to add modifiers to events from javascript side, because we don't rely on mpl.js we did pick up the changes from that side, only the python side.

**Comment by ianhi** [comment]
Thanks again for reporting @Linusnie ! The fix has been merged, trying to remember how to make a release now - once that's done version `0.9.3` and up should work with latest matplotlib

**Comment by ianhi** [comment]
@Linusnie should be fixed in the now release version `0.9.3`

**Comment by Linusnie** [comment]
@ianhi awesome! thanks for the quick response

**Comment by Sciroccogti** [comment]
Is it really fixed? `ipympl=0.9.3` with `matplotlib=3.7.0` still get the same error.
